"""Pydantic models matching Anthropic's Messages API schema.

This module re-exports all models for convenient imports:
    from src.models import MessagesRequest, MessagesResponse
"""

from .batches import (
    BatchesListResponse,
    BatchRequest,
    BatchRequestParams,
    BatchResult,
    BatchResultLine,
    CanceledResult,
    CreateBatchRequest,
    ErroredResult,
    ExpiredResult,
    MessageBatch,
    MessageBatchDeletedResponse,
    ProcessingStatus,
    RequestCounts,
    SucceededResult,
)
from .errors import (
    ErrorDetail,
    ErrorResponse,
    ErrorType,
    SDKMessageMode,
)
from .files import (
    FileDeletedResponse,
    FileMetadata,
    FilesListResponse,
)
from .requests import (
    CacheControl,
    ContentBlock,
    ContentBlockDocument,
    ContentBlockImage,
    ContentBlockText,
    CountTokensRequest,
    DocumentSource,
    ImageSource,
    Message,
    MessagesRequest,
    ThinkingConfig,
    ToolDefinition,
    ToolResultBlock,
    ToolUseBlock,
)
from .responses import (
    CountTokensResponse,
    MessagesResponse,
    ModelInfo,
    ModelsListResponse,
    RedactedThinkingBlock,
    ResponseContentBlock,
    StopReason,
    TextBlock,
    ThinkingBlock,
    ToolUseResponseBlock,
    Usage,
)
from .streaming import (
    ContentBlockDelta,
    ContentBlockDeltaEvent,
    ContentBlockDeltaText,
    ContentBlockDeltaThinking,
    ContentBlockDeltaToolInput,
    ContentBlockStartEvent,
    ContentBlockStopEvent,
    ErrorEvent,
    MessageDelta,
    MessageDeltaEvent,
    MessageDeltaUsage,
    MessageStartEvent,
    MessageStopEvent,
    PingEvent,
    StreamEvent,
)

__all__ = [
    # Errors
    "SDKMessageMode",
    "ErrorType",
    "ErrorDetail",
    "ErrorResponse",
    # Requests
    "CacheControl",
    "ImageSource",
    "DocumentSource",
    "ContentBlockText",
    "ContentBlockImage",
    "ContentBlockDocument",
    "ToolUseBlock",
    "ToolResultBlock",
    "ContentBlock",
    "Message",
    "ToolDefinition",
    "ThinkingConfig",
    "MessagesRequest",
    "CountTokensRequest",
    # Responses
    "Usage",
    "TextBlock",
    "ThinkingBlock",
    "RedactedThinkingBlock",
    "ToolUseResponseBlock",
    "ResponseContentBlock",
    "StopReason",
    "MessagesResponse",
    "ModelInfo",
    "ModelsListResponse",
    "CountTokensResponse",
    # Files
    "FileMetadata",
    "FileDeletedResponse",
    "FilesListResponse",
    # Batches
    "BatchRequestParams",
    "BatchRequest",
    "CreateBatchRequest",
    "RequestCounts",
    "ProcessingStatus",
    "MessageBatch",
    "MessageBatchDeletedResponse",
    "BatchesListResponse",
    "SucceededResult",
    "ErroredResult",
    "CanceledResult",
    "ExpiredResult",
    "BatchResult",
    "BatchResultLine",
    # Streaming
    "MessageStartEvent",
    "ContentBlockStartEvent",
    "ContentBlockDeltaText",
    "ContentBlockDeltaThinking",
    "ContentBlockDeltaToolInput",
    "ContentBlockDelta",
    "ContentBlockDeltaEvent",
    "ContentBlockStopEvent",
    "MessageDeltaUsage",
    "MessageDelta",
    "MessageDeltaEvent",
    "MessageStopEvent",
    "PingEvent",
    "ErrorEvent",
    "StreamEvent",
]
